version: "3.4"

x-common-variables:
  MYSQL_USER: ${MYSQL_USER}
  MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  MYSQL_DATABASE: ${MYSQL_DATABASE}
  REACT_APP_SERVER_PORT: ${REACT_APP_SERVER_PORT}

services:
  mysql-db:
    image: mysql:${MYSQL_VERSION}
    container_name: mysql_web
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - 3306:3306
    restart: unless-stopped
    volumes:
      - ./db/knownet.sql:/docker-entrypoint-initdb.d/knownet.sql
  phpmyadmin:
    depends_on:
      - mysql-db
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_container_web
    environment:
      PMA_HOST: mysql-db
    links:
      - mysql-db:mysql-db
    ports:
      - 8080:80
    restart: always
  server:
    build: ./server
    container_name: node_server_container_web
    depends_on:
      - mysql-db
    environment:
      MYSQL_HOST_IP: ${MYSQL_HOST_IP}
    ports:
      - 8000:8000
    volumes:
      - ./server:/app
    links:
      - mysql-db
    command: npm start
  client:
    build: ./client
    container_name: client_container_web
    environment:
      NODE_PATH: ${NODE_PATH}
    ports:
      - 3000:3000
    volumes:
      - ./client/src:/app/src
    links:
      - server
    command: npm start
